Repository cds-snc/covid-alert-app, pull requests merged in 2021-05, with the labels that each got.

#1556 Add the correct schema for detox ios tests.
  .detoxrc.json
Labels: apple, fixed

#1557 Feature/clear outbreak history
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
  src/screens/exposureHistory/ExposureHistoryScreen.tsx
  src/services/OutbreakService/OutbreakService.ts
Labels: high priority

#1548 Updates and Fixes for e2e
  e2e/README.md
  e2e/SetupToRunDetox.png
  e2e/SuccesfulDemoMenuTest.png
  e2e/exploreDemoMenu.e2e.js
  e2e/java.md
  src/screens/home/views/OutbreakExposedView.tsx
  src/services/ExposureNotificationService/ExposureNotificationService.ts
  test-gallery/README.md
Labels: documentation, enhancement

#1578 Align yarn run-ios simulator config with Detox configs
  package.json
Labels: apple

#1635 Update close button (toolbar) Language select
  src/screens/language/Language.tsx
Labels: v2

#1634 Update close button (toolbar) for region picker
  src/screens/regionPicker/RegionPickerSettings.tsx
Labels: v2

#1633 Update card text - Enable COVID Alert
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
Labels: v2

#1632 Un-nest tip box
  src/screens/home/components/Tip.tsx
  src/screens/home/views/DiagnosedView.tsx
Labels: v2

#1629 Toggle what to do if your exposed menu button
  src/screens/menu/MenuScreen.tsx
Labels: v2

#1628 Font fix "notosans" vs "Noto Sans"
  src/screens/onboarding/views/Anonymous.tsx
  src/screens/onboarding/views/Permissions.tsx
Labels: v2

#1630 Update recent exposure text
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
Labels: v2

#1637 Update `how it works` close button
  src/screens/tutorial/Tutorial.tsx
Labels: v2

#1643 Config cleanup
  react-native.config.js
Labels: cleanup

#1636 QR code box styling
  src/screens/qr/views/QRCodeScanner.tsx
Labels: v2

#1644 Remove outdated TEST_PLAN file
  TEST_PLAN.md
Labels: cleanup

#1642 Remove unused db.json
  db.json
Labels: cleanup

#1641 Removing appcenter file
  appcenter-post-clone.sh
Labels: cleanup

#1640 Remove unused .yml file
  dev.yml
Labels: cleanup

#1639 Remove unused design dir and files
  design/aftereffects/locationping.aep
  design/aftereffects/onboarding-new.aep
  design/aftereffects/onboarding.aep
  design/aftereffects/phone.ai
  design/illustrator/bubble.ai
  design/illustrator/dinger.ai
  design/illustrator/illustrations.ai
  design/illustrator/ringer.ai
  design/illustrator/sounds.ai
Labels: cleanup
