Repository cds-snc/covid-alert-app, pull requests merged in 2021-06, with the labels that each got.

#1624 Figma/Styling/Content Updates
  src/components/InfoButton.tsx
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
  src/locale/translations/region.json
  src/locale/translations/regional/en.json
  src/locale/translations/regional/fr.json
  src/locale/translations/regional/index.js
  src/screens/datasharing/IntermediateInstructionScreen.tsx
  src/screens/datasharing/TekUploadSubsequentDays.tsx
  src/screens/exposureHistory/ExposureHistoryScreen.tsx
  src/screens/exposureHistory/views/ExposureList.tsx
  src/screens/home/components/AllSetView.tsx
  src/screens/home/components/Tip.tsx
  src/screens/home/views/ClearExposureView.tsx
  src/screens/home/views/ClearOutbreakExposureView.tsx
  src/screens/home/views/DiagnosedView.tsx
  src/screens/nocode/NoCode.tsx
Labels: v2

#1650 added content body
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
  src/screens/qr/CheckInHistoryScreen.tsx
Labels: v2

#1651 Remove fork doc
  FORK.md
Labels: cleanup

#1653 Add Readme ref for regional content
  README.md
Labels: cleanup

#1660 updated en and fr content
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
Labels: content

#1658 fixed datepicker voice over for both iOS and android
  ios/Podfile.lock
  package.json
  src/components/ButtonSelect.tsx
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
  src/screens/datasharing/components/DatePicker.tsx
  yarn.lock
Labels: a11y

#1666 MainNavigator cleanup
  src/navigation/MainNavigator.tsx
Labels: cleanup

#1669 Remove extra data spy mockImplementation
  src/services/ExposureNotificationService/tests/ExposureNotificationService.spec.ts
Labels: cleanup

#1683 Auto delete visits after 28 days
  src/services/OutbreakService/OutbreakService.spec.ts
  src/services/OutbreakService/OutbreakService.ts
  src/services/OutbreakService/tests/utils.ts
Labels: v2

#1685 Update readme - iOS local development
  README.md
Labels: cleanup

#1688 Update PR template
  .github/pull_request_template.md
Labels: cleanup

#1692 Update poll notification doc
  docs/notifications/readme.md
Labels: cleanup

#1694 Remove link to removed test doc
  README.md
Labels: cleanup

#1693 Update Readme overview
  README.md
Labels: cleanup

#1700 Remove unused date mock
  src/services/ExposureNotificationService/tests/ExposureNotificationService.spec.ts
Labels: cleanup

#1704 Minor test cleanup
  src/services/ExposureNotificationService/tests/ExposureNotificationService.spec.ts
Labels: cleanup

#1706 Refactored periodSinceLastCheck
  src/services/ExposureNotificationService/ExposureNotificationService.ts
  src/services/ExposureNotificationService/tests/ExposureNotificationService.spec.ts
  src/services/OutbreakService/OutbreakService.ts
  src/shared/config.ts
  src/shared/date-fns.ts
Labels: cleanup

#1712 Help detect missing or empty translation strings
  package.json
  translation-keys.js
Labels: cleanup

#1713 Translation string cleanup
  src/locale/translations/en.json
  src/locale/translations/fr.json
  src/locale/translations/index.js
Labels: cleanup

#1715 Check translation keys on generate
  package.json
  translation-keys.js
Labels: cleanup

#1710 Chore/date locale clean up
  src/locale/locale.tsx
  src/screens/datasharing/components/DatePicker.tsx
  src/screens/exposureHistory/views/ExposureList.tsx
  src/screens/exposureHistory/views/OutbreakExposureContent.tsx
  src/screens/home/views/ExposureDateView.tsx
  src/screens/home/views/OutbreakExposedView.tsx
  src/screens/qr/CheckInHistoryScreen.tsx
  src/screens/qr/CheckInSuccessfulScreen.tsx
Labels: cleanup

#1714 Clean up of unused or repeated code.
  src/screens/datasharing/IntermediateInstructionScreen.tsx
  src/screens/datasharing/Step0Screen.tsx
  src/screens/datasharing/Step2Screen.tsx
  src/screens/datasharing/SymptomOnsetDateScreen.tsx
  src/screens/datasharing/TestDateScreen.tsx
  src/screens/datasharing/components/BaseDataSharingView.tsx
  src/screens/datasharing/components/BaseTekUploadView.tsx
  src/screens/exposureHistory/ExposureHistoryScreen.tsx
  src/screens/home/views/ClearExposureView.tsx
  src/screens/home/views/ClearOutbreakExposureView.tsx
  src/screens/language/Language.tsx
  src/screens/nocode/NoCode.tsx
  src/screens/onboarding/OnboardingContent.tsx
  src/screens/onboarding/views/Anonymous.tsx
  src/screens/onboarding/views/Permissions.tsx
  src/screens/qr-onboarding/TutorialContent.tsx
  src/screens/qr/InvalidQRCodeScreen.tsx
  src/screens/qr/components/BaseQRCodeScreen.tsx
  src/screens/qr/views/CameraPermissionDenied.tsx
  src/screens/regionPicker/RegionPickerExposed.tsx
  src/screens/regionPicker/RegionPickerExposedNoPT.tsx
  src/screens/regionPicker/RegionPickerSettings.tsx
  src/screens/regionPicker/RegionPickerShared.tsx
  src/screens/testScreen/components/RadioButtons.tsx
  src/screens/tutorial/TutorialContent.tsx
  src/shared/Styles.js
  src/shared/theme/default.ts
Labels: cleanup

#1727 Remove qr code placeholder images
  src/assets/qr-code-onboard-1.png
  src/assets/qr-code-onboard-2.png
  src/assets/qr-code-onboard-3.png
Labels: cleanup
